/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XaiRouteImport } from './routes/xai'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as DamageRouteImport } from './routes/damage'
import { Route as AnomalyRouteImport } from './routes/anomaly'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const XaiRoute = XaiRouteImport.update({
  id: '/xai',
  path: '/xai',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageRoute = DamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyRoute = AnomalyRouteImport.update({
  id: '/anomaly',
  path: '/anomaly',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/anomaly': typeof AnomalyRoute
  '/damage': typeof DamageRoute
  '/maintenance': typeof MaintenanceRoute
  '/report': typeof ReportRoute
  '/risk': typeof RiskRoute
  '/xai': typeof XaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/anomaly': typeof AnomalyRoute
  '/damage': typeof DamageRoute
  '/maintenance': typeof MaintenanceRoute
  '/report': typeof ReportRoute
  '/risk': typeof RiskRoute
  '/xai': typeof XaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/anomaly': typeof AnomalyRoute
  '/damage': typeof DamageRoute
  '/maintenance': typeof MaintenanceRoute
  '/report': typeof ReportRoute
  '/risk': typeof RiskRoute
  '/xai': typeof XaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/anomaly'
    | '/damage'
    | '/maintenance'
    | '/report'
    | '/risk'
    | '/xai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/anomaly'
    | '/damage'
    | '/maintenance'
    | '/report'
    | '/risk'
    | '/xai'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/anomaly'
    | '/damage'
    | '/maintenance'
    | '/report'
    | '/risk'
    | '/xai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AnomalyRoute: typeof AnomalyRoute
  DamageRoute: typeof DamageRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ReportRoute: typeof ReportRoute
  RiskRoute: typeof RiskRoute
  XaiRoute: typeof XaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xai': {
      id: '/xai'
      path: '/xai'
      fullPath: '/xai'
      preLoaderRoute: typeof XaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage': {
      id: '/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof DamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly': {
      id: '/anomaly'
      path: '/anomaly'
      fullPath: '/anomaly'
      preLoaderRoute: typeof AnomalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AnomalyRoute: AnomalyRoute,
  DamageRoute: DamageRoute,
  MaintenanceRoute: MaintenanceRoute,
  ReportRoute: ReportRoute,
  RiskRoute: RiskRoute,
  XaiRoute: XaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
